
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 10.0.19045 - AMD64
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "build-emc/_deps/raylib-src/cmake/AddIfFlagCompiles.cmake:3 (CHECK_C_COMPILER_FLAG)"
      - "build-emc/_deps/raylib-src/cmake/CompilerFlags.cmake:5 (add_if_flag_compiles)"
      - "build-emc/_deps/raylib-src/CMakeLists.txt:34 (include)"
    checks:
      - "Performing Test COMPILER_HAS_THOSE_TOGGLES"
    directories:
      source: "C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/CMakeFiles/CMakeScratch/TryCompile-4j6531"
      binary: "C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/CMakeFiles/CMakeScratch/TryCompile-4j6531"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "C:/devTools/mingw64/bin/clang-scan-deps.exe"
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: "-s USE_GLFW=3"
      CMAKE_MODULE_PATH: "C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/_deps/raylib-src/cmake"
    buildResult:
      variable: "COMPILER_HAS_THOSE_TOGGLES"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/CMakeFiles/CMakeScratch/TryCompile-4j6531'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/devTools/mingw64/bin/mingw32-make.exe -f Makefile cmTC_262c6/fast
        C:/devTools/mingw64/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_262c6.dir\\build.make CMakeFiles/cmTC_262c6.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/CMakeFiles/CMakeScratch/TryCompile-4j6531'
        Building C object CMakeFiles/cmTC_262c6.dir/src.c.o
        C:\\devTools\\emsdk\\upstream\\emscripten\\emcc.bat -DCOMPILER_HAS_THOSE_TOGGLES  -Werror=pointer-arith -MD -MT CMakeFiles/cmTC_262c6.dir/src.c.o -MF CMakeFiles\\cmTC_262c6.dir\\src.c.o.d -o CMakeFiles\\cmTC_262c6.dir\\src.c.o -c C:\\Users\\Brett\\Desktop\\devFiles\\lpr\\lpr-solver-tool\\build-emc\\CMakeFiles\\CMakeScratch\\TryCompile-4j6531\\src.c
        Linking C executable cmTC_262c6.js
        "C:\\Program Files\\CMake\\bin\\cmake.exe" -E cmake_link_script CMakeFiles\\cmTC_262c6.dir\\link.txt --verbose=1
        C:\\devTools\\emsdk\\upstream\\emscripten\\emcc.bat -s USE_GLFW=3  @CMakeFiles\\cmTC_262c6.dir\\objects1.rsp -o cmTC_262c6.js 
        mingw32-make[1]: Leaving directory 'C:/Users/Brett/Desktop/devFiles/lpr/lpr-solver-tool/build-emc/CMakeFiles/CMakeScratch/TryCompile-4j6531'
        
      exitCode: 0
...
